package app.pinya.lime.domain.model

enum class StringPref {
    HOME_ALIGNMENT,
    HOME_DOUBLE_TAP_ACTION,
    HOME_DOUBLE_TAP_APP,
    HOME_SWIPE_UP_ACTION,
    HOME_SWIPE_UP_APP,
    HOME_SWIPE_DOWN_ACTION,
    HOME_SWIPE_DOWN_APP,

    TIME_FORMAT,
    TIME_CLICK_APP,

    DATE_FORMAT,
    DATE_CLICK_APP,
}