name: LimeLauncher Build & Publish Debug APK

on:
  push:
  pull_request:
    branches:
      - main
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
          java-version: '17'
          distribution: 'temurin'

    - name: Fix git safe.directory in container 
      run: mkdir -p /home/runner/work/_temp/_github_home && printf "[safe]\n\tdirectory = /github/workspace" > /home/runner/work/_temp/_github_home/.gitconfig          
    - name: Make Workspace writeable
      run: git config --global --add safe.directory /github/workspace
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    - name: Generate version.txt for Hub release
      run: ./gradlew generateVersionTxt
    - name: Releasing using Hub
      uses: valley-fordham/action-release-debugapk@master
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       APP_FOLDER: app
       RELEASE_TITLE: LimeLauncher Build
